### ISSUE TITLE
Chill support

### ISSUE THREAD

**Issue by wpank** [paritytech/ledgeracio#28]
We ideally will want to send `chill` txs from the validator (this being sort of the inverse of the announce command).

This allows us to stop validating, move servers or upgrade, and then validate again.

Example use cases:
`./ledgeracio --network kusama validator chill 1` will send a `staking.chill` tx from the address at the index specified.

**Comment by dvdplm** [comment]
@Demi-Marie #32 did not include docs, so we can't close this yet.

**Comment by DemiMarie** [comment]
Fixed by https://github.com/paritytech/ledgeracio/commit/bc20c8cd7294e197f7c89958d0e24228d6b7f346
